[global]
includeSetupCommands = true
setupCommands = [
    "curl https://install.python-poetry.org | python3 -",
    "export PATH=\"$HOME/.local/bin:$PATH\"",
    "poetry install",
    "poetry run streamlit run Frontend/Accueil.py"
]